#!/bin/bash
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
sed -i -e 's/\r$//' $script_path/config.sh
source $script_path/config.sh
source $script_path/functions.sh

bookingid=$1

echo "bookingid = $bookingid"

file=$script_path/xml/getportfolio-$bookingid.xml

xml='xml=<?xml version="1.0"?>
<request xmlns="http://fusionapi.traveltek.net/1.0/xsds"> 
    <auth username="'${ca_tt_username}'" password="'${ca_tt_password}'" /> 
    <method action="getportfolio" sitename="ignite.site.traveltek.net" bookingid="'${bookingid}'" externalreference="" />
</request>'

curl -o $file -X POST --url "https://fusionapi.traveltek.net/1.0/backoffice.pl/getportfolio" \
		-H "Content-Type: application/x-www-form-urlencoded" \
		-d "$xml" 

#REMOVE THE NAMESPACE FROM THE XML OR XMLSTARLET CAN PROCESS IT
sed -i 's/xmlns="http:\/\/fusionapi.traveltek.net\/1.0\/xsds"/ /g' $file
xmlstarlet ed --inplace -r "response/results/result/bookingdetails/passengers" -v passenger_details $file

mysql --login-path=local --skip-column-names --local-infile --execute="USE "$ca_db_name";
DELETE FROM "$ca_db_table_prefix"_portfolio_transfer WHERE bookingid = $bookingid;

LOAD XML LOCAL INFILE '$file' 
REPLACE
INTO TABLE "$ca_db_table_prefix"_portfolio_transfer
ROWS IDENTIFIED BY '<transfers>'
	(accommodation,
	additionalinfo,
	adults,
	arrivalflighttime,
	atol,
	bookingformreceived,
	bookingid,
	bookingreference,
	children,
	commission,
	commissionable,
	commissionrate,
	confirmationreceived,
	costingid,
	datebooked,
	deleted,
	departureflighttime,
	depdate,
	displayorder,
	documentname,
	dropoffdate,
	dropoffdetail,
	dropofftype,
	elementbookedby,
	engine,
	faretype,
	grossprice,
	id,
	infants,
	localid,
	maxpassengers,
	nettprice,
	originalstatus,
	ownerid,
	paymentdatetype,
	paymentduedays,
	paymentduetype,
	penaltiesdate,
	pickupdate,
	pickupdetail,
	pickupresort,
	pickuptype,
	returndate,
	sellprice,
	shipname,
	status,
	supplier,
	supplierid,
	suppliername,
	termsandconditionsurl,
	ticketsreceived,
	type,
	unitsrequired,
	vat,
	vatrequirement,
	vehicle,
	voucherurl);

DELETE FROM "$ca_db_table_prefix"_portfolio_cruise WHERE bookingid = $bookingid;

LOAD XML LOCAL INFILE '$file' 
REPLACE
INTO TABLE "$ca_db_table_prefix"_portfolio_cruise
ROWS IDENTIFIED BY '<cruise>'
	(additionalinfo,
	airportcode,
	arrdate,
	arrives,
	atol,
	bookingformreceived,
	bookingid,
	bookingreference,
	codetocruiseid,
	commission,
	commissionable,
	commissionrate,
	confirmationreceived,
	costingid,
	cruisefaretype,
	cruisename,
	cruisenumber,
	datebooked,
	deleted,
	departs,
	depdate,
	depositduedate,
	diningseating,
	diningsmoking,
	displayorder,
	documentname,
	duration,
	elementbookedby,
	enddate,
	engine,
	finalpaymentdate,
	grossprice,
	homeported,
	id,
	lineid,
	linename,
	localid,
	lockliveamends,
	nettprice,
	obstructedview,
	onboardcredit,
	originalstatus,
	ownerid,
	paymentdatetype,
	paymentduedays,
	paymentduetype,
	penaltiesdate,
	region,
	returndate,
	sellprice,
	shipid,
	shipname,
	shiprating,
	startdate,
	status,
	supplier,
	supplierid,
	suppliername,
	tablesize,
	termsandconditionsurl,
	ticketsreceived,
	type,
	vat,
	vatrequirement,
	voucherurl);

DELETE FROM "$ca_db_table_prefix"_portfolio_flight WHERE bookingid = $bookingid;

LOAD XML LOCAL INFILE '$file' 
REPLACE
INTO TABLE "$ca_db_table_prefix"_portfolio_flight
ROWS IDENTIFIED BY '<flight>'
	(
	atol,
	bookingformreceived,
	bookingid,
	bookingreference,
	carriers,
	commission,
	commissionable,
	commissionrate,
	confirmationreceived,
	costingid,
	datebooked,
	deleted,
	depair,
	depdate,
	destair,
	destname,
	displayorder,
	documentname,
	duration,
	elementbookedby,
	engine,
	flightbaggageallowance,
	grossprice,
	hasbaggage,
	id,
	immediateticket,
	inarrivecode,
	inarrivedate,
	indepartcode,
	indepartdate,
	indepartname,
	localid,
	nettprice,
	oneway,
	originalstatus,
	outarrivecode,
	outarrivedate,
	outarrivename,
	outdepartcode,
	outdepartdate,
	ownerid,
	paymentdatetype,
	paymentduedays,
	paymentduetype,
	penaltiesdate,
	region,
	returndate,
	status,
	supplier,
	supplierid,
	suppliername,
	termsandconditionsurl,
	ticketoption,
	ticketsreceived,
	tickettimelimit,
	totalextras,
	type,
	ukonly,
	vat,
	vatrequirement,
	voucherurl);

DELETE FROM "$ca_db_table_prefix"_portfolio_attraction WHERE bookingid = $bookingid;

LOAD XML LOCAL INFILE '$file' 
REPLACE
INTO TABLE "$ca_db_table_prefix"_portfolio_attraction
ROWS IDENTIFIED BY '<attraction>'
(
	additionalinfo,
	airportcode,
	atol,
	bookingformreceived,
	bookingid,
	bookingreference,
	commission,
	commissionable,
	commissionrate,
	confirmationreceived,
	costingid,
	datebooked,
	deleted,
	depdate,
	description,
	destinationcountries,
	displayorder,
	documentname,
	duration,
	elementbookedby,
	enddate,
	engine,
	finalpaymentdate,
	grossprice,
	id,
	localid,
	location,
	name,
	nettprice,
	originalstatus,
	ownerid,
	paymentdatetype,
	paymentduedays,
	paymentduetype,
	penaltiesdate,
	sellprice,
	startdate,
	status,
	supplier,
	supplierid,
	suppliername,
	termsandconditionsurl,
	ticketsreceived,
	type,
	vat,
	vatrequirement,
	voucherurl
);

DELETE FROM "$ca_db_table_prefix"_portfolio_accom WHERE bookingid = $bookingid;

LOAD XML LOCAL INFILE '$file' 
REPLACE
INTO TABLE "$ca_db_table_prefix"_portfolio_accom
ROWS IDENTIFIED BY '<accom>'
(
	additionalinfo,
	address1,
	address2,
	address3,
	address4,
	atol,
	boardbasis,
	bookingformreceived,
	bookingid,
	bookingreference,
	cancellationpolicy,
	checkin,
	checkout,
	commission,
	commissionable,
	commissionrate,
	confirmationreceived,
	contactname,
	contactphone,
	costingid,
	datebooked,
	deleted,
	depdate,
	description,
	destcode,
	destcountry,
	displayorder,
	documentname,
	elementbookedby,
	engine,
	essentialinfo,
	grossprice,
	handlingaddress,
	handlingagent,
	hotelagentref,
	hotelname,
	id,
	keycollection,
	lastupdated,
	localid,
	nettprice,
	numbernights, 
	originalstatus,
	ownerid,
	paymentdatetype,
	paymentduedays,
	paymentduetype,
	penaltiesdate,
	propertyid,
	propertyreference,
	propertytype,
	rating,
	resort,
	returndate,
	sellprice,
	status,
	supplier,
	supplierid,
	suppliername,
	termsandconditionsurl,
	ticketsreceived,
	type,
	vat,
	vatrequirement,
	voucherurl
);

DELETE FROM "$ca_db_table_prefix"_portfolio_passenger WHERE bookingid = $bookingid;

LOAD XML LOCAL INFILE '$file' 
REPLACE
INTO TABLE "$ca_db_table_prefix"_portfolio_passenger
ROWS IDENTIFIED BY '<passenger_details>'
(
	address1,
	address2,
	address3,
	address4,
	age,
	altemail,
	altphone,
	bookingid,
	country,
	countryisocode,
	created,
	deleted,
	deletedby,
	deletedon,
	dob,
	email,
	emergencyemail,
	emergencyname,
	emergencyphone,
	faxnumber,
	firstname,
	gender,
	holidaymakerid,
	id,
	insuranceassistancecompany,
	insurancecompany,
	insurancepolicynumber,
	insurancetelnumber,
	lastname,
	lastupdated,
	lastupdatedby,
	leadpassenger,
	localid,
	loyaltynumber,
	mealoption,
	middlename,
	mobile,
	nationality,
	nationalityisocode,
	nokaddress1,
	nokaddress2,
	nokaddress3,
	nokaddress4,
	nokname,
	nokphone,
	nokrelationship,
	ownerid,
	passdocumenttype,
	passport,
	passportauthority,
	passportexpirydate,
	passportissuecountry,
	passportissuecountryisocode,
	passportissuedate,
	passportplaceofissue,
	paxguid,
	placeofbirth,
	postcode,
	redress,
	specialservices,
	telephone,
	title,
	titleid,
	type
);"



